-- =====================================================
-- SMART SELLER SHOP - COMPLETE SUPABASE DATABASE
-- =====================================================

-- 1. PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  role text NOT NULL DEFAULT 'customer',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profiles_role_check
    CHECK (role IN ('customer', 'admin'))
);

-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  price numeric(12,2) NOT NULL DEFAULT 0,
  image_url text,
  stock integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT products_price_check CHECK (price >= 0),
  CONSTRAINT products_stock_check CHECK (stock >= 0)
);

-- اگر products پہلے سے موجود تھا تو category_id لازمی add ہوگا
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS category_id bigint;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS name text;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS description text;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS price numeric(12,2) DEFAULT 0;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS image_url text;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- category relation
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'products_category_id_fkey'
  ) THEN
    ALTER TABLE public.products
    ADD CONSTRAINT products_category_id_fkey
    FOREIGN KEY (category_id)
    REFERENCES public.categories(id)
    ON DELETE SET NULL;
  END IF;
END $$;

-- 4. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  total numeric(12,2) NOT NULL DEFAULT 0,
  shipping_name text,
  shipping_phone text,
  shipping_address text,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT orders_status_check
    CHECK (
      status IN (
        'pending',
        'confirmed',
        'processing',
        'shipped',
        'delivered',
        'cancelled'
      )
    ),

  CONSTRAINT orders_total_check CHECK (total >= 0)
);

-- 5. ORDER ITEMS
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  quantity integer NOT NULL DEFAULT 1,
  price numeric(12,2) NOT NULL DEFAULT 0,

  CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT order_items_price_check CHECK (price >= 0)
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS products_category_idx
ON public.products(category_id);

CREATE INDEX IF NOT EXISTS products_active_idx
ON public.products(is_active);

CREATE INDEX IF NOT EXISTS orders_customer_idx
ON public.orders(customer_id);

CREATE INDEX IF NOT EXISTS orders_status_idx
ON public.orders(status);

CREATE INDEX IF NOT EXISTS order_items_order_idx
ON public.order_items(order_id);

CREATE INDEX IF NOT EXISTS order_items_product_idx
ON public.order_items(product_id);

-- =====================================================
-- ENABLE ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- POLICIES
-- =====================================================

-- PRODUCTS: everyone can see active products
DROP POLICY IF EXISTS "Anyone can view active products"
ON public.products;

CREATE POLICY "Anyone can view active products"
ON public.products
FOR SELECT
USING (is_active = true);

-- CATEGORIES: everyone can view
DROP POLICY IF EXISTS "Anyone can view categories"
ON public.categories;

CREATE POLICY "Anyone can view categories"
ON public.categories
FOR SELECT
USING (true);

-- PROFILES: user can see own profile
DROP POLICY IF EXISTS "Users can view own profile"
ON public.profiles;

CREATE POLICY "Users can view own profile"
ON public.profiles
FOR SELECT
USING (auth.uid() = id);

-- PROFILES: user can create own profile
DROP POLICY IF EXISTS "Users can create own profile"
ON public.profiles;

CREATE POLICY "Users can create own profile"
ON public.profiles
FOR INSERT
WITH CHECK (auth.uid() = id);

-- PROFILES: user can update own profile
DROP POLICY IF EXISTS "Users can update own profile"
ON public.profiles;

CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id);

-- ORDERS: customer can see own orders
DROP POLICY IF EXISTS "Customers can view own orders"
ON public.orders;

CREATE POLICY "Customers can view own orders"
ON public.orders
FOR SELECT
USING (auth.uid() = customer_id);

-- ORDERS: customer can create own orders
DROP POLICY IF EXISTS "Customers can create own orders"
ON public.orders;

CREATE POLICY "Customers can create own orders"
ON public.orders
FOR INSERT
WITH CHECK (auth.uid() = customer_id);

-- ORDER ITEMS: customer can see items of own orders
DROP POLICY IF EXISTS "Customers can view own order items"
ON public.order_items;

CREATE POLICY "Customers can view own order items"
ON public.order_items
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.orders
    WHERE orders.id = order_items.order_id
    AND orders.customer_id = auth.uid()
  )
);

-- ORDER ITEMS: customer can add items to own order
DROP POLICY IF EXISTS "Customers can create own order items"
ON public.order_items;

CREATE POLICY "Customers can create own order items"
ON public.order_items
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.orders
    WHERE orders.id = order_items.order_id
    AND orders.customer_id = auth.uid()
  )
);

-- =====================================================
-- DONE
-- =====================================================
